// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StaffRole struct {
	ID       int32
	RoleName string
}

type Temple struct {
	ID           pgtype.UUID
	NameTh       string
	NameEn       string
	Location     pgtype.Point
	AddressTh    *string
	AddressEn    *string
	ContactPhone *string
	FoundedOn    pgtype.Date
}

type TempleDonation struct {
	ID             pgtype.UUID
	TempleID       pgtype.UUID
	UserID         pgtype.UUID
	TempleEventID  pgtype.UUID
	DonorName      *string
	DonationAmount pgtype.Numeric
	DonationDate   pgtype.Date
	Purpose        *string
	CreatedAt      pgtype.Timestamp
}

type TempleEvent struct {
	ID             pgtype.UUID
	TempleID       pgtype.UUID
	Title          string
	Description    *string
	EventStartDate pgtype.Date
	EventEndDate   pgtype.Date
}

type TempleImage struct {
	ID       pgtype.UUID
	TempleID pgtype.UUID
	ImageUrl string
	Caption  *string
}

type TempleMembership struct {
	ID             pgtype.UUID
	TempleID       pgtype.UUID
	MemberName     string
	MembershipDate pgtype.Date
	MembershipType string
}

type TempleNews struct {
	ID          pgtype.UUID
	TempleID    pgtype.UUID
	NewsTitle   string
	NewsContent string
	CreatedAt   pgtype.Timestamp
}

type TempleReview struct {
	ID          pgtype.UUID
	TempleID    pgtype.UUID
	UserID      pgtype.UUID
	Title       *string
	Description *string
	Rating      *int32
	CreatedAt   pgtype.Timestamp
}

type TempleSchedule struct {
	ID           pgtype.UUID
	TempleID     pgtype.UUID
	ScheduleDate pgtype.Date
	ScheduleTime pgtype.Time
	Activity     string
}

type TempleSponsorship struct {
	ID                pgtype.UUID
	TempleID          pgtype.UUID
	SponsorName       string
	SponsorshipAmount pgtype.Numeric
	SponsorshipDate   pgtype.Date
	Purpose           *string
}

type TempleStaff struct {
	ID          pgtype.UUID
	TempleID    pgtype.UUID
	UserID      pgtype.UUID
	StaffName   string
	RoleID      *int32
	Position    string
	ContactInfo *string
}

type User struct {
	ID        pgtype.UUID
	Username  string
	ImageUrl  *string
	Password  string
	Email     *string
	CreatedAt pgtype.Timestamp
}

type UserAccount struct {
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	AccessToken    *string
	RefreshToken   *string
	TokenExpiry    pgtype.Timestamp
}
