// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Temple struct {
	ID            pgtype.UUID
	ThaiName      string
	RomanizedName string
	Location      pgtype.Point
	AddressTh     pgtype.Text
	AddressEn     pgtype.Text
	ContactPhone  pgtype.Text
	FoundedOn     pgtype.Date
}

type TempleDonation struct {
	ID             pgtype.UUID
	TempleID       pgtype.UUID
	DonorName      string
	DonationAmount pgtype.Numeric
	DonationDate   pgtype.Date
	Purpose        pgtype.Text
}

type TempleEvent struct {
	ID          pgtype.UUID
	TempleID    pgtype.UUID
	EventName   string
	EventDate   pgtype.Date
	Description pgtype.Text
}

type TempleImage struct {
	ID       pgtype.UUID
	TempleID pgtype.UUID
	ImageUrl string
	Caption  pgtype.Text
}

type TempleMembership struct {
	ID             pgtype.UUID
	TempleID       pgtype.UUID
	MemberName     string
	MembershipDate pgtype.Date
	MembershipType string
}

type TempleNews struct {
	ID          pgtype.UUID
	TempleID    pgtype.UUID
	NewsTitle   string
	NewsContent string
	NewsDate    pgtype.Date
}

type TempleReview struct {
	ID           pgtype.UUID
	TempleID     pgtype.UUID
	ReviewText   string
	ReviewRating pgtype.Int4
	ReviewDate   pgtype.Date
}

type TempleSchedule struct {
	ID           pgtype.UUID
	TempleID     pgtype.UUID
	ScheduleDate pgtype.Date
	ScheduleTime pgtype.Time
	Activity     string
}

type TempleSponsorship struct {
	ID                pgtype.UUID
	TempleID          pgtype.UUID
	SponsorName       string
	SponsorshipAmount pgtype.Numeric
	SponsorshipDate   pgtype.Date
	Purpose           pgtype.Text
}

type TempleStaff struct {
	ID          pgtype.UUID
	TempleID    pgtype.UUID
	StaffName   string
	Position    string
	ContactInfo pgtype.Text
}
