// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTemple = `-- name: GetTemple :one
SELECT id, thai_name, romanized_name, location, address_th, address_en, contact_phone, founded_on FROM temples
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTemple(ctx context.Context, id pgtype.UUID) (Temple, error) {
	row := q.db.QueryRow(ctx, getTemple, id)
	var i Temple
	err := row.Scan(
		&i.ID,
		&i.ThaiName,
		&i.RomanizedName,
		&i.Location,
		&i.AddressTh,
		&i.AddressEn,
		&i.ContactPhone,
		&i.FoundedOn,
	)
	return i, err
}

const listTemples = `-- name: ListTemples :many
SELECT id, thai_name, romanized_name, location, address_th, address_en, contact_phone, founded_on FROM temples
ORDER BY thai_name
`

func (q *Queries) ListTemples(ctx context.Context) ([]Temple, error) {
	rows, err := q.db.Query(ctx, listTemples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Temple
	for rows.Next() {
		var i Temple
		if err := rows.Scan(
			&i.ID,
			&i.ThaiName,
			&i.RomanizedName,
			&i.Location,
			&i.AddressTh,
			&i.AddressEn,
			&i.ContactPhone,
			&i.FoundedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
